/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import View.event.EventMenu;
import java.awt.Color;
import java.awt.Component;

/**
 *
 * @author PIERO
 */
public class JF_Main extends javax.swing.JFrame {

    /**
     * Creates new form JF_Main
     */
    public JF_Main() {
        initComponents();
        //panelSlideCustomer.setVisible(false);
        /*EventMenu event = new EventMenu() {
            @Override
            public void selected(int index) {
                if (index == 0) {
                    //showForm(new Form_1());
                } else if (index == 8) {
                    System.out.println("Logout");
                } else {
                    //showForm(new Form(index));
                }
            }
        };
        
        jP_Menu1.initMenu(event);*/
    }
    
    private void showForm(Component com){
        body.removeAll();
        body.add(com);
        body.revalidate();
        body.repaint();       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel1 = new View.swing.RoundPanel();
        body = new javax.swing.JPanel();
        jP_Menu1 = new View.JP_Menu();
        panelSlide = new View.Slide.PanelSlide();
        panelSlideCustomer = new View.Slide.PanelSlide();
        panelSlideEmployee = new View.Slide.PanelSlide();
        panelSlideSupplier = new View.Slide.PanelSlide();
        panelSlideProduct = new View.Slide.PanelSlide();
        panelProfile = new javax.swing.JPanel();
        panelCategory = new javax.swing.JPanel();
        panelReport = new javax.swing.JPanel();
        panelPurchase = new javax.swing.JPanel();
        panelSale = new javax.swing.JPanel();
        panelDashboard = new javax.swing.JPanel();
        header1 = new View.component.Header();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        roundPanel1.setBackground(new java.awt.Color(21, 21, 21));
        roundPanel1.setMaximumSize(new java.awt.Dimension(500, 500));

        body.setOpaque(false);
        body.setLayout(new java.awt.BorderLayout());

        panelSlide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout panelSlideCustomerLayout = new javax.swing.GroupLayout(panelSlideCustomer);
        panelSlideCustomer.setLayout(panelSlideCustomerLayout);
        panelSlideCustomerLayout.setHorizontalGroup(
            panelSlideCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        panelSlideCustomerLayout.setVerticalGroup(
            panelSlideCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        panelSlide.add(panelSlideCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 670));

        javax.swing.GroupLayout panelSlideEmployeeLayout = new javax.swing.GroupLayout(panelSlideEmployee);
        panelSlideEmployee.setLayout(panelSlideEmployeeLayout);
        panelSlideEmployeeLayout.setHorizontalGroup(
            panelSlideEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelSlideEmployeeLayout.setVerticalGroup(
            panelSlideEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        panelSlide.add(panelSlideEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 670));

        javax.swing.GroupLayout panelSlideSupplierLayout = new javax.swing.GroupLayout(panelSlideSupplier);
        panelSlideSupplier.setLayout(panelSlideSupplierLayout);
        panelSlideSupplierLayout.setHorizontalGroup(
            panelSlideSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        panelSlideSupplierLayout.setVerticalGroup(
            panelSlideSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        panelSlide.add(panelSlideSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 670));

        javax.swing.GroupLayout panelSlideProductLayout = new javax.swing.GroupLayout(panelSlideProduct);
        panelSlideProduct.setLayout(panelSlideProductLayout);
        panelSlideProductLayout.setHorizontalGroup(
            panelSlideProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        panelSlideProductLayout.setVerticalGroup(
            panelSlideProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        panelSlide.add(panelSlideProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 670));

        javax.swing.GroupLayout panelProfileLayout = new javax.swing.GroupLayout(panelProfile);
        panelProfile.setLayout(panelProfileLayout);
        panelProfileLayout.setHorizontalGroup(
            panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        panelProfileLayout.setVerticalGroup(
            panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        panelSlide.add(panelProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 670));

        javax.swing.GroupLayout panelCategoryLayout = new javax.swing.GroupLayout(panelCategory);
        panelCategory.setLayout(panelCategoryLayout);
        panelCategoryLayout.setHorizontalGroup(
            panelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        panelCategoryLayout.setVerticalGroup(
            panelCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        panelSlide.add(panelCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 670));

        javax.swing.GroupLayout panelReportLayout = new javax.swing.GroupLayout(panelReport);
        panelReport.setLayout(panelReportLayout);
        panelReportLayout.setHorizontalGroup(
            panelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        panelReportLayout.setVerticalGroup(
            panelReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        panelSlide.add(panelReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 670));

        javax.swing.GroupLayout panelPurchaseLayout = new javax.swing.GroupLayout(panelPurchase);
        panelPurchase.setLayout(panelPurchaseLayout);
        panelPurchaseLayout.setHorizontalGroup(
            panelPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        panelPurchaseLayout.setVerticalGroup(
            panelPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        panelSlide.add(panelPurchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 670));

        javax.swing.GroupLayout panelSaleLayout = new javax.swing.GroupLayout(panelSale);
        panelSale.setLayout(panelSaleLayout);
        panelSaleLayout.setHorizontalGroup(
            panelSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        panelSaleLayout.setVerticalGroup(
            panelSaleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        panelSlide.add(panelSale, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 670));

        javax.swing.GroupLayout panelDashboardLayout = new javax.swing.GroupLayout(panelDashboard);
        panelDashboard.setLayout(panelDashboardLayout);
        panelDashboardLayout.setHorizontalGroup(
            panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        panelDashboardLayout.setVerticalGroup(
            panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        panelSlide.add(panelDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 670));

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP_Menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addComponent(panelSlide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))))
            .addComponent(header1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addComponent(jP_Menu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(9, 9, 9))
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addComponent(body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelSlide, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel body;
    public View.component.Header header1;
    public View.JP_Menu jP_Menu1;
    public javax.swing.JPanel panelCategory;
    public javax.swing.JPanel panelDashboard;
    public javax.swing.JPanel panelProfile;
    public javax.swing.JPanel panelPurchase;
    public javax.swing.JPanel panelReport;
    public javax.swing.JPanel panelSale;
    public View.Slide.PanelSlide panelSlide;
    public View.Slide.PanelSlide panelSlideCustomer;
    public View.Slide.PanelSlide panelSlideEmployee;
    public View.Slide.PanelSlide panelSlideProduct;
    public View.Slide.PanelSlide panelSlideSupplier;
    private View.swing.RoundPanel roundPanel1;
    // End of variables declaration//GEN-END:variables
}
