/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Category;
import Model.Supplier;
import View.TableCustom.TableCustom;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author PIERO
 */
public class JF_System extends javax.swing.JFrame {

    /**
     * Creates new form JF_System
     */
    public JF_System() {
        initComponents();

        ShapedButtonUI roundUI = new ShapedButtonUI();
        roundUI.setShape(ShapedButton.ButtonShape.ROUND,btn_category_register);
        btn_category_register.setUI(roundUI);
        
        roundUI.setShape(ShapedButton.ButtonShape.ROUND,btn_category_update);
        btn_category_update.setUI(roundUI);
        
        roundUI.setShape(ShapedButton.ButtonShape.ROUND,btn_profile_update);
        btn_profile_update.setUI(roundUI);
        
        ShapedButtonUICancel roundUIc = new ShapedButtonUICancel();
        roundUIc.setShape(ShapedButton.ButtonShape.ROUND, btn_new_purchase);
        btn_new_purchase.setUI(roundUIc);
        
        roundUIc.setShape(ShapedButton.ButtonShape.ROUND, btn_category_cancel);
        btn_category_cancel.setUI(roundUIc);

        TableCustom.apply(jScrollPane6, TableCustom.TableType.DEFAULT);
        TableCustom.apply(jScrollPane2, TableCustom.TableType.DEFAULT);
        

        
        btn_remove_purchase.setVisible(false);
        btn_category_update.setVisible(false);
        btn_category_delete.setVisible(false);
        btn_category_cancel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JP_Products = new javax.swing.JPanel();
        lbl_products = new javax.swing.JLabel();
        JP_Purchases = new javax.swing.JPanel();
        lbl_purchases = new javax.swing.JLabel();
        JP_Sales = new javax.swing.JPanel();
        lbl_sales = new javax.swing.JLabel();
        JP_Customers = new javax.swing.JPanel();
        lbl_customers = new javax.swing.JLabel();
        JP_Employees = new javax.swing.JPanel();
        lbl_employees = new javax.swing.JLabel();
        JP_Suppliers = new javax.swing.JPanel();
        lbl_suppliers = new javax.swing.JLabel();
        JP_Categories = new javax.swing.JPanel();
        lbl_categories = new javax.swing.JLabel();
        JP_Reports = new javax.swing.JPanel();
        lbl_reports = new javax.swing.JLabel();
        JP_Settings = new javax.swing.JPanel();
        lbl_settings = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_photo = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        lbl_employee_name = new javax.swing.JLabel();
        lbl_employee_rol = new javax.swing.JLabel();
        JTPanel = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        tableScrollButton2 = new View.TableCustom.TableScrollButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_purchase = new javax.swing.JTable();
        txt_purchase_product_code = new View.TextField();
        txt_purchase_product_name = new View.TextField();
        txt_purchase_amount = new View.TextField();
        cmb_product_supplier = new View.ComboBoxSuggestion<>();
        txt_purchase_price = new View.TextField();
        txt_purchase_id = new View.TextField();
        jPanelRound8 = new LIB.JPanelRound();
        txt_purchase_total_to_pay = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        btn_add_product_to_buy = new javax.swing.JButton();
        btn_confirm_purchase = new javax.swing.JButton();
        btn_remove_purchase = new javax.swing.JButton();
        btn_new_purchase = new javax.swing.JButton();
        txt_purchase_subtotal = new View.TextField();
        jPanel19 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        table_sale = new javax.swing.JTable();
        txt_sale_product_code = new View.TextField();
        txt_sale_product_id = new View.TextField();
        txt_sale_product_name = new View.TextField();
        txt_sale_price = new View.TextField();
        txt_sale_subtotal = new View.TextField();
        txt_sale_stock = new View.TextField();
        txt_sale_quantity = new View.TextField();
        txt_sale_customer_document = new View.TextField();
        txt_sale_total_to_pay = new View.TextField();
        txt_sale_customer_name = new View.TextField();
        btn_sale_add_product = new javax.swing.JButton();
        btn_sale_confirm = new javax.swing.JButton();
        btn_sale_delete = new javax.swing.JButton();
        btn_sale_new = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanelRound1 = new LIB.JPanelRound();
        jLabel32 = new javax.swing.JLabel();
        txt_category_search = new javax.swing.JTextField();
        tableScrollButton1 = new View.TableCustom.TableScrollButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        table_category = new javax.swing.JTable();
        txt_category_id = new View.TextField();
        txt_category_name = new View.TextField();
        btn_category_delete = new javax.swing.JButton();
        btn_category_cancel = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        btn_category_update = new javax.swing.JButton();
        btn_category_register = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        table_all_sale = new javax.swing.JTable();
        jLabel62 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        table_all_purchase = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txt_profile_modify_password = new View.PasswordField();
        txt_profile_confirm_password = new View.PasswordField();
        btn_profile_update = new javax.swing.JButton();
        jPanelRound2 = new LIB.JPanelRound();
        txt_profile_name = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanelRound3 = new LIB.JPanelRound();
        txt_profile_telephone = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanelRound4 = new LIB.JPanelRound();
        txt_profile_id = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPanelRound5 = new LIB.JPanelRound();
        txt_profile_address = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jPanelRound6 = new LIB.JPanelRound();
        txt_profile_email = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jPanelRound7 = new LIB.JPanelRound();
        txt_profile_rol = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(18, 45, 61));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JP_Products.setBackground(new java.awt.Color(18, 45, 61));

        lbl_products.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_products.setForeground(new java.awt.Color(255, 255, 255));
        lbl_products.setText("Products");

        javax.swing.GroupLayout JP_ProductsLayout = new javax.swing.GroupLayout(JP_Products);
        JP_Products.setLayout(JP_ProductsLayout);
        JP_ProductsLayout.setHorizontalGroup(
            JP_ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_products, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        JP_ProductsLayout.setVerticalGroup(
            JP_ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_products, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel1.add(JP_Products, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, 35));

        JP_Purchases.setBackground(new java.awt.Color(18, 45, 61));

        lbl_purchases.setBackground(new java.awt.Color(18, 45, 61));
        lbl_purchases.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_purchases.setForeground(new java.awt.Color(255, 255, 255));
        lbl_purchases.setText("Purchases");

        javax.swing.GroupLayout JP_PurchasesLayout = new javax.swing.GroupLayout(JP_Purchases);
        JP_Purchases.setLayout(JP_PurchasesLayout);
        JP_PurchasesLayout.setHorizontalGroup(
            JP_PurchasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_purchases, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        JP_PurchasesLayout.setVerticalGroup(
            JP_PurchasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_purchases, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel1.add(JP_Purchases, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 200, 35));

        JP_Sales.setBackground(new java.awt.Color(18, 45, 61));

        lbl_sales.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_sales.setForeground(new java.awt.Color(255, 255, 255));
        lbl_sales.setText("Sales");

        javax.swing.GroupLayout JP_SalesLayout = new javax.swing.GroupLayout(JP_Sales);
        JP_Sales.setLayout(JP_SalesLayout);
        JP_SalesLayout.setHorizontalGroup(
            JP_SalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_sales, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        JP_SalesLayout.setVerticalGroup(
            JP_SalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_sales, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel1.add(JP_Sales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 200, 35));

        JP_Customers.setBackground(new java.awt.Color(18, 45, 61));

        lbl_customers.setBackground(new java.awt.Color(18, 45, 61));
        lbl_customers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_customers.setForeground(new java.awt.Color(255, 255, 255));
        lbl_customers.setText("Customers");

        javax.swing.GroupLayout JP_CustomersLayout = new javax.swing.GroupLayout(JP_Customers);
        JP_Customers.setLayout(JP_CustomersLayout);
        JP_CustomersLayout.setHorizontalGroup(
            JP_CustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_customers, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        JP_CustomersLayout.setVerticalGroup(
            JP_CustomersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_customers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel1.add(JP_Customers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 200, 35));

        JP_Employees.setBackground(new java.awt.Color(18, 45, 61));

        lbl_employees.setBackground(new java.awt.Color(18, 45, 61));
        lbl_employees.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_employees.setForeground(new java.awt.Color(255, 255, 255));
        lbl_employees.setText("Employees");

        javax.swing.GroupLayout JP_EmployeesLayout = new javax.swing.GroupLayout(JP_Employees);
        JP_Employees.setLayout(JP_EmployeesLayout);
        JP_EmployeesLayout.setHorizontalGroup(
            JP_EmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_employees, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        JP_EmployeesLayout.setVerticalGroup(
            JP_EmployeesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_employees, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel1.add(JP_Employees, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 35));

        JP_Suppliers.setBackground(new java.awt.Color(18, 45, 61));

        lbl_suppliers.setBackground(new java.awt.Color(18, 45, 61));
        lbl_suppliers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_suppliers.setForeground(new java.awt.Color(255, 255, 255));
        lbl_suppliers.setText("Suppliers");

        javax.swing.GroupLayout JP_SuppliersLayout = new javax.swing.GroupLayout(JP_Suppliers);
        JP_Suppliers.setLayout(JP_SuppliersLayout);
        JP_SuppliersLayout.setHorizontalGroup(
            JP_SuppliersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_suppliers, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        JP_SuppliersLayout.setVerticalGroup(
            JP_SuppliersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_suppliers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel1.add(JP_Suppliers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 200, 35));

        JP_Categories.setBackground(new java.awt.Color(18, 45, 61));

        lbl_categories.setBackground(new java.awt.Color(18, 45, 61));
        lbl_categories.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_categories.setForeground(new java.awt.Color(255, 255, 255));
        lbl_categories.setText("Categories");

        javax.swing.GroupLayout JP_CategoriesLayout = new javax.swing.GroupLayout(JP_Categories);
        JP_Categories.setLayout(JP_CategoriesLayout);
        JP_CategoriesLayout.setHorizontalGroup(
            JP_CategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_categories, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        JP_CategoriesLayout.setVerticalGroup(
            JP_CategoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_categories, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel1.add(JP_Categories, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 200, 35));

        JP_Reports.setBackground(new java.awt.Color(18, 45, 61));

        lbl_reports.setBackground(new java.awt.Color(18, 45, 61));
        lbl_reports.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_reports.setForeground(new java.awt.Color(255, 255, 255));
        lbl_reports.setText("Reports");

        javax.swing.GroupLayout JP_ReportsLayout = new javax.swing.GroupLayout(JP_Reports);
        JP_Reports.setLayout(JP_ReportsLayout);
        JP_ReportsLayout.setHorizontalGroup(
            JP_ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_reports, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        JP_ReportsLayout.setVerticalGroup(
            JP_ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_reports, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel1.add(JP_Reports, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 200, 35));

        JP_Settings.setBackground(new java.awt.Color(18, 45, 61));

        lbl_settings.setBackground(new java.awt.Color(18, 45, 61));
        lbl_settings.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_settings.setForeground(new java.awt.Color(255, 255, 255));
        lbl_settings.setText("Settings");

        javax.swing.GroupLayout JP_SettingsLayout = new javax.swing.GroupLayout(JP_Settings);
        JP_Settings.setLayout(JP_SettingsLayout);
        JP_SettingsLayout.setHorizontalGroup(
            JP_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_settings, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        JP_SettingsLayout.setVerticalGroup(
            JP_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_settings, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel1.add(JP_Settings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 200, 35));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 200, 580));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 100));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 100));

        jPanel3.setBackground(new java.awt.Color(18, 45, 61));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PHARMACY");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 340, 40));
        jPanel3.add(btn_photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 80, 65));

        btn_logout.setText("Logout");
        jPanel3.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 35, -1, 30));

        lbl_employee_name.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        lbl_employee_name.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lbl_employee_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 130, 30));

        lbl_employee_rol.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lbl_employee_rol.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(lbl_employee_rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, 130, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1010, 100));

        JTPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_purchase.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        table_purchase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name Product", "Amount", "Price", "Subtotal", "Supplier", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_purchase);
        if (table_purchase.getColumnModel().getColumnCount() > 0) {
            table_purchase.getColumnModel().getColumn(0).setResizable(false);
            table_purchase.getColumnModel().getColumn(0).setPreferredWidth(15);
            table_purchase.getColumnModel().getColumn(1).setResizable(false);
            table_purchase.getColumnModel().getColumn(1).setPreferredWidth(80);
            table_purchase.getColumnModel().getColumn(2).setResizable(false);
            table_purchase.getColumnModel().getColumn(3).setResizable(false);
            table_purchase.getColumnModel().getColumn(4).setResizable(false);
            table_purchase.getColumnModel().getColumn(5).setResizable(false);
        }

        tableScrollButton2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel5.add(tableScrollButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 950, 160));

        txt_purchase_product_code.setLabelText("Code Product");
        txt_purchase_product_code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_purchase_product_codeKeyTyped(evt);
            }
        });
        jPanel5.add(txt_purchase_product_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 180, -1));

        txt_purchase_product_name.setEditable(false);
        txt_purchase_product_name.setLabelText("Name Product");
        txt_purchase_product_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_purchase_product_nameActionPerformed(evt);
            }
        });
        jPanel5.add(txt_purchase_product_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 180, -1));

        txt_purchase_amount.setLabelText("Amount");
        txt_purchase_amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_purchase_amountKeyTyped(evt);
            }
        });
        jPanel5.add(txt_purchase_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 180, -1));
        jPanel5.add(cmb_product_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 180, 35));

        txt_purchase_price.setLabelText("Purchase Price");
        txt_purchase_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_purchase_priceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_purchase_priceKeyTyped(evt);
            }
        });
        jPanel5.add(txt_purchase_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 210, -1));

        txt_purchase_id.setEditable(false);
        txt_purchase_id.setLabelText("N° Identificación");
        txt_purchase_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_purchase_idActionPerformed(evt);
            }
        });
        jPanel5.add(txt_purchase_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 120, -1));

        jPanelRound8.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRound8.setColorPrimario(new java.awt.Color(255, 255, 255));
        jPanelRound8.setColorSecundario(new java.awt.Color(255, 255, 255));
        jPanelRound8.setOpaque(true);

        txt_purchase_total_to_pay.setEditable(false);
        txt_purchase_total_to_pay.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        txt_purchase_total_to_pay.setBorder(null);
        txt_purchase_total_to_pay.setOpaque(false);
        txt_purchase_total_to_pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_purchase_total_to_payActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(180, 180, 180));
        jLabel25.setText("Total Price");

        javax.swing.GroupLayout jPanelRound8Layout = new javax.swing.GroupLayout(jPanelRound8);
        jPanelRound8.setLayout(jPanelRound8Layout);
        jPanelRound8Layout.setHorizontalGroup(
            jPanelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound8Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(txt_purchase_total_to_pay, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelRound8Layout.setVerticalGroup(
            jPanelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRound8Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel25)
                .addGap(3, 3, 3)
                .addComponent(txt_purchase_total_to_pay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        jPanel5.add(jPanelRound8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 230, -1));

        btn_add_product_to_buy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_add_product_to_buy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addpurchasex64.png"))); // NOI18N
        btn_add_product_to_buy.setBorder(null);
        btn_add_product_to_buy.setContentAreaFilled(false);
        btn_add_product_to_buy.setFocusPainted(false);
        btn_add_product_to_buy.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addpurchase2x64.png"))); // NOI18N
        jPanel5.add(btn_add_product_to_buy, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 80, 70));

        btn_confirm_purchase.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_confirm_purchase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buyx64.png"))); // NOI18N
        btn_confirm_purchase.setBorder(null);
        btn_confirm_purchase.setContentAreaFilled(false);
        btn_confirm_purchase.setFocusPainted(false);
        btn_confirm_purchase.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buy2x64.png"))); // NOI18N
        jPanel5.add(btn_confirm_purchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 230, 80, 70));

        btn_remove_purchase.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_remove_purchase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/purchase_cancelx64.png"))); // NOI18N
        btn_remove_purchase.setBorder(null);
        btn_remove_purchase.setContentAreaFilled(false);
        jPanel5.add(btn_remove_purchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 120, 70, -1));

        btn_new_purchase.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btn_new_purchase.setForeground(new java.awt.Color(255, 255, 255));
        btn_new_purchase.setText("CANCELAR");
        btn_new_purchase.setBorder(null);
        jPanel5.add(btn_new_purchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 310, 120, 30));

        txt_purchase_subtotal.setEditable(false);
        txt_purchase_subtotal.setLabelText("Subtotal");
        jPanel5.add(txt_purchase_subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 210, -1));

        JTPanel.addTab("Purchases", jPanel5);

        jPanel19.setBackground(new java.awt.Color(153, 203, 203));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_sale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Product", "Name", "Quatity", "Sale Price", "Subtotal", "Customer Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(table_sale);

        jPanel19.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 920, 150));

        txt_sale_product_code.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txt_sale_product_code.setLabelText("Product Code");
        txt_sale_product_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sale_product_codeActionPerformed(evt);
            }
        });
        txt_sale_product_code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_sale_product_codeKeyTyped(evt);
            }
        });
        jPanel19.add(txt_sale_product_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 170, -1));

        txt_sale_product_id.setEditable(false);
        txt_sale_product_id.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txt_sale_product_id.setLabelText("N° Identificación");
        jPanel19.add(txt_sale_product_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 130, -1));

        txt_sale_product_name.setEditable(false);
        txt_sale_product_name.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txt_sale_product_name.setLabelText("Product Name");
        jPanel19.add(txt_sale_product_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 170, -1));

        txt_sale_price.setEditable(false);
        txt_sale_price.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txt_sale_price.setLabelText("Price");
        jPanel19.add(txt_sale_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 170, -1));

        txt_sale_subtotal.setEditable(false);
        txt_sale_subtotal.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txt_sale_subtotal.setLabelText("Subtotal");
        jPanel19.add(txt_sale_subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 170, -1));

        txt_sale_stock.setEditable(false);
        txt_sale_stock.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txt_sale_stock.setLabelText("Stock");
        jPanel19.add(txt_sale_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 170, -1));

        txt_sale_quantity.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txt_sale_quantity.setLabelText("Quantity");
        txt_sale_quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_sale_quantityKeyTyped(evt);
            }
        });
        jPanel19.add(txt_sale_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 170, -1));

        txt_sale_customer_document.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txt_sale_customer_document.setLabelText("Document");
        jPanel19.add(txt_sale_customer_document, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 170, -1));

        txt_sale_total_to_pay.setEditable(false);
        txt_sale_total_to_pay.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txt_sale_total_to_pay.setLabelText("Total to pay");
        jPanel19.add(txt_sale_total_to_pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 170, -1));

        txt_sale_customer_name.setEditable(false);
        txt_sale_customer_name.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txt_sale_customer_name.setLabelText("Customer Name");
        jPanel19.add(txt_sale_customer_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 170, -1));

        btn_sale_add_product.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_sale_add_product.setText("Add");
        jPanel19.add(btn_sale_add_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 60, 105, 30));

        btn_sale_confirm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_sale_confirm.setText("Sell");
        jPanel19.add(btn_sale_confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, 105, 30));

        btn_sale_delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_sale_delete.setText("Delete");
        jPanel19.add(btn_sale_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 170, 105, 30));

        btn_sale_new.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_sale_new.setText("New");
        jPanel19.add(btn_sale_new, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 220, 105, 30));

        JTPanel.addTab("Sales", jPanel19);

        jPanel6.setBackground(new java.awt.Color(153, 203, 203));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        JTPanel.addTab("Customers", jPanel6);

        jPanel7.setBackground(new java.awt.Color(153, 203, 203));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        JTPanel.addTab("Employees", jPanel7);

        jPanel8.setBackground(new java.awt.Color(153, 203, 203));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        JTPanel.addTab("Suppliers", jPanel8);

        jPanelRound1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRound1.setColorPrimario(new java.awt.Color(255, 255, 255));
        jPanelRound1.setColorSecundario(new java.awt.Color(255, 255, 255));
        jPanelRound1.setOpaque(true);
        jPanelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.x32png.png"))); // NOI18N
        jPanelRound1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 40, 40));

        txt_category_search.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        txt_category_search.setBorder(null);
        txt_category_search.setOpaque(false);
        jPanelRound1.add(txt_category_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 5, 180, 30));

        table_category.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(table_category);

        tableScrollButton1.add(jScrollPane6, java.awt.BorderLayout.CENTER);

        txt_category_id.setEditable(false);
        txt_category_id.setLabelText("N° Identificación");

        txt_category_name.setLabelText("Name Category");

        btn_category_delete.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        btn_category_delete.setText("DELETE");
        btn_category_delete.setBorder(null);
        btn_category_delete.setContentAreaFilled(false);

        btn_category_cancel.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        btn_category_cancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_category_cancel.setText("CANCEL");
        btn_category_cancel.setBorder(null);
        btn_category_cancel.setContentAreaFilled(false);

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_category_update.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        btn_category_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_category_update.setText("UPDATE");
        btn_category_update.setBorder(null);
        btn_category_update.setContentAreaFilled(false);
        jPanel12.add(btn_category_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 170, 40));

        btn_category_register.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        btn_category_register.setForeground(new java.awt.Color(255, 255, 255));
        btn_category_register.setText("REGISTER");
        btn_category_register.setBorder(null);
        btn_category_register.setContentAreaFilled(false);
        jPanel12.add(btn_category_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 170, 40));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 312, Short.MAX_VALUE)
                .addComponent(btn_category_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(tableScrollButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btn_category_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_category_id, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_category_name, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_category_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(txt_category_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(txt_category_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_category_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tableScrollButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        JTPanel.addTab("Categories", jPanel9);

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("PURCHASES");
        jLabel44.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel10.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 370, -1));

        table_all_sale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice Sale", "Customer", "Employee", "Total", "Sale Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(table_all_sale);

        jPanel10.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 91, 925, 183));

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel62.setText("SALES");
        jLabel62.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel10.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 156, 30));

        table_all_purchase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice Purchase", "Supplier", "Total", "Sale Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(table_all_purchase);

        jPanel10.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 339, 925, 122));

        JTPanel.addTab("Reports", jPanel10);

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/userx256.png"))); // NOI18N
        jPanel11.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 240));

        txt_profile_modify_password.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txt_profile_modify_password.setLabelText("Modify Password");
        txt_profile_modify_password.setLineColor(new java.awt.Color(119, 153, 60));
        txt_profile_modify_password.setSelectionColor(new java.awt.Color(213, 234, 218));
        txt_profile_modify_password.setShowAndHide(true);
        jPanel11.add(txt_profile_modify_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, 220, -1));

        txt_profile_confirm_password.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txt_profile_confirm_password.setLabelText("Confirm Password");
        txt_profile_confirm_password.setLineColor(new java.awt.Color(119, 153, 60));
        txt_profile_confirm_password.setSelectionColor(new java.awt.Color(213, 234, 218));
        txt_profile_confirm_password.setShowAndHide(true);
        jPanel11.add(txt_profile_confirm_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, 220, -1));

        btn_profile_update.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        btn_profile_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_profile_update.setText("UPDATE");
        jPanel11.add(btn_profile_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 250, 170, 40));

        jPanelRound2.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRound2.setColorPrimario(new java.awt.Color(255, 255, 255));
        jPanelRound2.setColorSecundario(new java.awt.Color(255, 255, 255));
        jPanelRound2.setOpaque(true);

        txt_profile_name.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        txt_profile_name.setBorder(null);
        txt_profile_name.setOpaque(false);
        txt_profile_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_profile_nameActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(180, 180, 180));
        jLabel19.setText("Full Name");

        javax.swing.GroupLayout jPanelRound2Layout = new javax.swing.GroupLayout(jPanelRound2);
        jPanelRound2.setLayout(jPanelRound2Layout);
        jPanelRound2Layout.setHorizontalGroup(
            jPanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(txt_profile_name, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelRound2Layout.setVerticalGroup(
            jPanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRound2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel19)
                .addGap(3, 3, 3)
                .addComponent(txt_profile_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        jPanel11.add(jPanelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 230, 55));

        jPanelRound3.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRound3.setColorPrimario(new java.awt.Color(255, 255, 255));
        jPanelRound3.setColorSecundario(new java.awt.Color(255, 255, 255));
        jPanelRound3.setOpaque(true);

        txt_profile_telephone.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        txt_profile_telephone.setBorder(null);
        txt_profile_telephone.setOpaque(false);
        txt_profile_telephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_profile_telephoneActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(180, 180, 180));
        jLabel20.setText("Telephone");

        javax.swing.GroupLayout jPanelRound3Layout = new javax.swing.GroupLayout(jPanelRound3);
        jPanelRound3.setLayout(jPanelRound3Layout);
        jPanelRound3Layout.setHorizontalGroup(
            jPanelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(txt_profile_telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelRound3Layout.setVerticalGroup(
            jPanelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRound3Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel20)
                .addGap(3, 3, 3)
                .addComponent(txt_profile_telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        jPanel11.add(jPanelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 230, -1));

        jPanelRound4.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRound4.setColorPrimario(new java.awt.Color(255, 255, 255));
        jPanelRound4.setColorSecundario(new java.awt.Color(255, 255, 255));
        jPanelRound4.setOpaque(true);

        txt_profile_id.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        txt_profile_id.setBorder(null);
        txt_profile_id.setOpaque(false);
        txt_profile_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_profile_idActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(180, 180, 180));
        jLabel21.setText("N° Identificación");

        javax.swing.GroupLayout jPanelRound4Layout = new javax.swing.GroupLayout(jPanelRound4);
        jPanelRound4.setLayout(jPanelRound4Layout);
        jPanelRound4Layout.setHorizontalGroup(
            jPanelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(txt_profile_id, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelRound4Layout.setVerticalGroup(
            jPanelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRound4Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel21)
                .addGap(3, 3, 3)
                .addComponent(txt_profile_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        jPanel11.add(jPanelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 230, -1));

        jPanelRound5.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRound5.setColorPrimario(new java.awt.Color(255, 255, 255));
        jPanelRound5.setColorSecundario(new java.awt.Color(255, 255, 255));
        jPanelRound5.setOpaque(true);

        txt_profile_address.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        txt_profile_address.setBorder(null);
        txt_profile_address.setOpaque(false);
        txt_profile_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_profile_addressActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(180, 180, 180));
        jLabel22.setText("Address");

        javax.swing.GroupLayout jPanelRound5Layout = new javax.swing.GroupLayout(jPanelRound5);
        jPanelRound5.setLayout(jPanelRound5Layout);
        jPanelRound5Layout.setHorizontalGroup(
            jPanelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(txt_profile_address, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelRound5Layout.setVerticalGroup(
            jPanelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRound5Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel22)
                .addGap(3, 3, 3)
                .addComponent(txt_profile_address, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        jPanel11.add(jPanelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 230, -1));

        jPanelRound6.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRound6.setColorPrimario(new java.awt.Color(255, 255, 255));
        jPanelRound6.setColorSecundario(new java.awt.Color(255, 255, 255));
        jPanelRound6.setOpaque(true);

        txt_profile_email.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        txt_profile_email.setBorder(null);
        txt_profile_email.setOpaque(false);
        txt_profile_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_profile_emailActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(180, 180, 180));
        jLabel23.setText("E-mail");

        javax.swing.GroupLayout jPanelRound6Layout = new javax.swing.GroupLayout(jPanelRound6);
        jPanelRound6.setLayout(jPanelRound6Layout);
        jPanelRound6Layout.setHorizontalGroup(
            jPanelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(txt_profile_email, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelRound6Layout.setVerticalGroup(
            jPanelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRound6Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel23)
                .addGap(3, 3, 3)
                .addComponent(txt_profile_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        jPanel11.add(jPanelRound6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 230, -1));

        jPanelRound7.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRound7.setColorPrimario(new java.awt.Color(255, 255, 255));
        jPanelRound7.setColorSecundario(new java.awt.Color(255, 255, 255));
        jPanelRound7.setOpaque(true);

        txt_profile_rol.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        txt_profile_rol.setBorder(null);
        txt_profile_rol.setOpaque(false);
        txt_profile_rol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_profile_rolActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(180, 180, 180));
        jLabel24.setText("Rol");

        javax.swing.GroupLayout jPanelRound7Layout = new javax.swing.GroupLayout(jPanelRound7);
        jPanelRound7.setLayout(jPanelRound7Layout);
        jPanelRound7Layout.setHorizontalGroup(
            jPanelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(txt_profile_rol, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelRound7Layout.setVerticalGroup(
            jPanelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRound7Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabel24)
                .addGap(3, 3, 3)
                .addComponent(txt_profile_rol, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        jPanel11.add(jPanelRound7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 230, -1));

        JTPanel.addTab("Profile", jPanel11);

        jPanel4.setBackground(new java.awt.Color(153, 203, 203));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        JTPanel.addTab("Products", jPanel4);

        getContentPane().add(JTPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 1010, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_profile_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_profile_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_profile_nameActionPerformed

    private void txt_profile_telephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_profile_telephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_profile_telephoneActionPerformed

    private void txt_profile_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_profile_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_profile_idActionPerformed

    private void txt_profile_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_profile_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_profile_addressActionPerformed

    private void txt_profile_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_profile_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_profile_emailActionPerformed

    private void txt_profile_rolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_profile_rolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_profile_rolActionPerformed

    private void txt_purchase_product_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_purchase_product_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_purchase_product_nameActionPerformed

    private void txt_purchase_total_to_payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_purchase_total_to_payActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_purchase_total_to_payActionPerformed

    private void txt_purchase_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_purchase_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_purchase_idActionPerformed

    private void txt_purchase_amountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_purchase_amountKeyTyped
        char c=evt.getKeyChar();
        if(c<'0'||c>'9'){
            evt.consume();
        }
        if(txt_purchase_amount.getText().length()>8){
            evt.consume();
        }
    }//GEN-LAST:event_txt_purchase_amountKeyTyped

    private void txt_purchase_product_codeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_purchase_product_codeKeyTyped
        char c=evt.getKeyChar();
        if(c<'0'||c>'9'){
            evt.consume();
        }
        if(txt_purchase_product_code.getText().length()>8){
            evt.consume();
        }
    }//GEN-LAST:event_txt_purchase_product_codeKeyTyped

    private void txt_purchase_priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_purchase_priceKeyTyped
        
        
        
        //Matcher matcher = Pattern.compile([0-9,]+[^.]).matcher(txt_purchase_price);
/*       
        int key = evt.getKeyChar();
        //char c=evt.getKeyChar();
        boolean numero = key >=48 && key <=57;
        boolean punto = key ==46;

        if(!(punto||numero)){
            evt.consume();
        }
        /*else if(c<'0'||c>'9'){
            evt.consume();
        }*/
        
       // if(txt_purchase_price.getText().length()>8){
       //     evt.consume();
       // }
    }//GEN-LAST:event_txt_purchase_priceKeyTyped

    private void txt_purchase_priceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_purchase_priceKeyReleased
        if(txt_purchase_price.getText().matches("^[0-9]+([.][0-9]+)?$")){
            evt.consume();
        };
    }//GEN-LAST:event_txt_purchase_priceKeyReleased

    private void txt_sale_product_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sale_product_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sale_product_codeActionPerformed

    private void txt_sale_product_codeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sale_product_codeKeyTyped
        char c=evt.getKeyChar();
        if(c<'0'||c>'9'){
            evt.consume();
        }
        if(txt_sale_product_code.getText().length()>8){
            evt.consume();
        }
    }//GEN-LAST:event_txt_sale_product_codeKeyTyped

    private void txt_sale_quantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_sale_quantityKeyTyped
        char c=evt.getKeyChar();
        if(c<'0'||c>'9'){
            evt.consume();
        }
        if(txt_sale_quantity.getText().length()>8){
            evt.consume();
        }
    }//GEN-LAST:event_txt_sale_quantityKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_System().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel JP_Categories;
    public javax.swing.JPanel JP_Customers;
    public javax.swing.JPanel JP_Employees;
    public javax.swing.JPanel JP_Products;
    public javax.swing.JPanel JP_Purchases;
    public javax.swing.JPanel JP_Reports;
    public javax.swing.JPanel JP_Sales;
    public javax.swing.JPanel JP_Settings;
    public javax.swing.JPanel JP_Suppliers;
    public javax.swing.JTabbedPane JTPanel;
    public javax.swing.JButton btn_add_product_to_buy;
    public javax.swing.JButton btn_category_cancel;
    public javax.swing.JButton btn_category_delete;
    public javax.swing.JButton btn_category_register;
    public javax.swing.JButton btn_category_update;
    public javax.swing.JButton btn_confirm_purchase;
    public javax.swing.JButton btn_logout;
    public javax.swing.JButton btn_new_purchase;
    private javax.swing.JButton btn_photo;
    public javax.swing.JButton btn_profile_update;
    public javax.swing.JButton btn_remove_purchase;
    public javax.swing.JButton btn_sale_add_product;
    public javax.swing.JButton btn_sale_confirm;
    public javax.swing.JButton btn_sale_delete;
    public javax.swing.JButton btn_sale_new;
    public View.ComboBoxSuggestion<Supplier> cmb_product_supplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private LIB.JPanelRound jPanelRound1;
    private LIB.JPanelRound jPanelRound2;
    private LIB.JPanelRound jPanelRound3;
    private LIB.JPanelRound jPanelRound4;
    private LIB.JPanelRound jPanelRound5;
    private LIB.JPanelRound jPanelRound6;
    private LIB.JPanelRound jPanelRound7;
    private LIB.JPanelRound jPanelRound8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    public javax.swing.JLabel lbl_categories;
    public javax.swing.JLabel lbl_customers;
    public javax.swing.JLabel lbl_employee_name;
    public javax.swing.JLabel lbl_employee_rol;
    public javax.swing.JLabel lbl_employees;
    public javax.swing.JLabel lbl_products;
    public javax.swing.JLabel lbl_purchases;
    public javax.swing.JLabel lbl_reports;
    public javax.swing.JLabel lbl_sales;
    public javax.swing.JLabel lbl_settings;
    public javax.swing.JLabel lbl_suppliers;
    private View.TableCustom.TableScrollButton tableScrollButton1;
    private View.TableCustom.TableScrollButton tableScrollButton2;
    public javax.swing.JTable table_all_purchase;
    public javax.swing.JTable table_all_sale;
    public javax.swing.JTable table_category;
    public javax.swing.JTable table_purchase;
    public javax.swing.JTable table_sale;
    public View.TextField txt_category_id;
    public View.TextField txt_category_name;
    public javax.swing.JTextField txt_category_search;
    public javax.swing.JTextField txt_profile_address;
    public View.PasswordField txt_profile_confirm_password;
    public javax.swing.JTextField txt_profile_email;
    public javax.swing.JTextField txt_profile_id;
    public View.PasswordField txt_profile_modify_password;
    public javax.swing.JTextField txt_profile_name;
    public javax.swing.JTextField txt_profile_rol;
    public javax.swing.JTextField txt_profile_telephone;
    public View.TextField txt_purchase_amount;
    public View.TextField txt_purchase_id;
    public View.TextField txt_purchase_price;
    public View.TextField txt_purchase_product_code;
    public View.TextField txt_purchase_product_name;
    public View.TextField txt_purchase_subtotal;
    public javax.swing.JTextField txt_purchase_total_to_pay;
    public View.TextField txt_sale_customer_document;
    public View.TextField txt_sale_customer_name;
    public View.TextField txt_sale_price;
    public View.TextField txt_sale_product_code;
    public View.TextField txt_sale_product_id;
    public View.TextField txt_sale_product_name;
    public View.TextField txt_sale_quantity;
    public View.TextField txt_sale_stock;
    public View.TextField txt_sale_subtotal;
    public View.TextField txt_sale_total_to_pay;
    // End of variables declaration//GEN-END:variables
}
